version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx-front
    ports:
      - "80:8000"
    volumes:
      - .:/app_data
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGOENV: production
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate
      && python manage.py get_currencies && python manage.py get_rates
      && python manage.py collectstatic --noinput
      && gunicorn currency_api.wsgi -b 0.0.0.0:8000 --workers 3"
    container_name: django
    volumes:
      - .:/app_data
    expose:
     - "8000"
