version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGOENV: development
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate
      && python manage.py get_currencies && python manage.py get_rates && python manage.py runserver 0.0.0.0:8000"
    container_name: currency_api
    volumes:
      - .:/app_data
    ports:
      - "8000:8000"