# Generated by Django 2.1.4 on 2018-12-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='euroexchangerate',
            options={'get_latest_by': 'date', 'ordering': ['-date', 'currency'], 'verbose_name': 'Euro Exchange Rate', 'verbose_name_plural': 'Euro Exchange Rates'},
        ),
    ]
